repos:
  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout
        args: ["--extra-keys", "metadata.language_info.version"]
  - repo: https://github.com/mwouts/jupytext
    rev: v1.13.7
    hooks:
    - id: jupytext
      args: [--sync, --from, ipynb, --to, ipynb, --update-metadata, '{"kernelspec": {"display_name": "Python 3 (ipykernel)", "language": "python", "name": "python3"}}']
