# Book settings
# Learn more at https://jupyterbook.org/customize/config.html
# This config builds the book without executing the notebooks first
# Execute notebooks first using nbmake, e.g.:
# pytest --numprocesses 2 --nbmake --overwrite
# (See .github/workflows/deploy.yml)

title: Swarm Notebooks
author: "Ashley Smith et al."
logo: ""
only_build_toc_files: true

execute:
  execute_notebooks: off

launch_buttons:
  notebook_interface        : jupyterlab
  jupyterhub_url            : "https://vre.vires.services"
  binderhub_url             : ""

repository:
  url: https://github.com/Swarm-DISC/Swarm_notebooks
  branch: master

html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button      : false
  extra_navbar              : Powered by <a href="https://jupyterbook.org">Jupyter Book</a>
  home_page_in_navbar       : true
  comments:
    hypothesis              : true
  announcement: '
    <div class="custom-header-container">
        <div>
            <a href="https://viresclient.readthedocs.io" target="_blank" class="link">viresclient</a>
            <a href="https://vires.services" target="_blank" class="link">VirES for Swarm</a>
            <a href="https://vre.vires.services" target="_blank" class="link">Swarm JupyterHub</a>
            <a href="" class="link-selected">Swarm Notebooks</a>
            <a href="https://swarmpal.readthedocs.io" target="_blank" class="link">SwarmPAL</a>
        </div>
    </div>

    <style>
        .custom-header-container {}

        .custom-header-container .link {
            margin: 0 10px;
            padding: 5px 10px;
            text-decoration: none;
            color: white;
        }

        .custom-header-container .link:hover {
            color: #1e90ff !important;
        }

        .custom-header-container .link-selected {
            margin: 0 10px;
            padding: 5px 10px;
            text-decoration: none;
            background-color: #ccc;
            color: black;
            border-radius: 5px;
        }
    </style>
  '

# See https://jupyterbook.org/content/content-blocks.html
parse:
  myst_enable_extensions:
    - dollarmath
    - linkify
    - substitution
    - colon_fence
    - deflist
