channels:
  - conda-forge
dependencies:
  # for eoxmagmod
  - fortran-compiler
  - cxx-compiler
  - make
  - conda-build
  - conda-verify
  # others
  - numpy
  - scipy
  - xarray
  - matplotlib
  - gdal
  - cartopy
  - cdflib
  - dask
  - pip
  - pip:
      - treebeard
      - watermark
      - viresclient
      - python-dotenv
      - hdf5storage # for chaosmagpy
      - netCDF4
