#!/usr/bin/env bash
set -euo pipefail
set -x

pip install swarmpyfac # Depends on packages in environment.yml
pip install chaosmagpy # depends on hdf5storage

# eoxmagmod installation
branch=staging
wget --no-verbose https://github.com/ESA-VirES/MagneticModel/archive/"$branch".zip -O MagneticModel.zip
unzip MagneticModel.zip
mv MagneticModel-"$branch" MagneticModel
conda build MagneticModel/libcdf
conda build MagneticModel/qdipole
conda install --quiet --yes --use-local qdipole cdf
pip install spacepy
# final part (pip install eoxmagmod) is in `start`