on:
  push:
    branches:
      - staging
      - master
  pull_request:
    branches:
      - staging
      - master
  workflow_dispatch:

# Only allow one such workflow to run at a time
# (since the supplied VirES tokens will only allow 2 max async jobs)
concurrency:
  group: ${{ github.workflow }}

env:
  PRODUCTION_TAG: '1.0.14'
  STAGING_TAG: '1.0.14'

jobs:
  book:
    name: Build Jupyter Book
    runs-on: ubuntu-latest
    steps:
      - name: Set run references
        run: |
          BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's|.*/||')
          GH_DEPLOY_ENV="${BRANCH_NAME}"
          ENABLE_GH_DEPLOY=$(if [[ "$BRANCH_NAME" == "master" || "$BRANCH_NAME" == "staging" ]]; then echo "true"; else echo "false"; fi)

          if [ "${{ github.event_name }}" == "pull_request" ]; then
            RUN_REF="pr${{ github.event.number }}"
            TARGET_BRANCH_NAME="${{ github.event.pull_request.base.ref }}"
          elif [ "${{ github.event_name }}" == "push" ]; then
            RUN_REF="${BRANCH_NAME}"
            TARGET_BRANCH_NAME=${BRANCH_NAME}
          elif [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            RUN_REF="${BRANCH_NAME}"
            TARGET_BRANCH_NAME="${BRANCH_NAME}"
          fi

          if [ "$TARGET_BRANCH_NAME" == "staging" ]; then
            VRE_TAG="${{ env.STAGING_TAG }}"
          else
            VRE_TAG="${{ env.PRODUCTION_TAG }}"
          fi

          echo "RUN_REF=${RUN_REF}" >> $GITHUB_ENV
          echo "TARGET_BRANCH_NAME=${TARGET_BRANCH_NAME}" >> $GITHUB_ENV
          echo "GH_DEPLOY_ENV=${GH_DEPLOY_ENV}" >> $GITHUB_ENV
          echo "ENABLE_GH_DEPLOY=${ENABLE_GH_DEPLOY}" >> $GITHUB_ENV
          echo "VRE_TAG=${VRE_TAG}" >> $GITHUB_ENV

      - uses: actions/checkout@v6

      - name: Login to Docker registry
        run: |
          echo ${{ secrets.EOX_REGISTRY_PASSWORD }} | docker login -u ${{ secrets.EOX_REGISTRY_USER }} --password-stdin registry.gitlab.eox.at

      - name: Build image
        run: make image

      - name: Fix workspace permissions for jovyan
        run: chmod -R a+w $GITHUB_WORKSPACE

      - name: Execute notebooks
        env:
          VIRES_TOKEN: ${{ secrets.VIRES_TOKEN }}
          VIRES_TOKEN_STAGING: ${{ secrets.VIRES_TOKEN_STAGING }}
          VIRES_TOKEN_STAGING_DISC: ${{ secrets.VIRES_TOKEN_STAGINGDISC }}
          TARGET_BRANCH: ${{ env.TARGET_BRANCH_NAME }}
        run: make execute

      - name: Build book
        if: always()
        run: make html

      - name: Deploy preview to Netlify
        if: always()
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './_build/html'
          production-deploy: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # RUN_REF is set to one of "master", "staging", "pr#"
          deploy-message: "Deploy from GitHub Actions (${{ env.RUN_REF }})"
          # Github deployment environment is one of "master", "staging"
          enable-github-deployment: ${{ env.ENABLE_GH_DEPLOY }}
          github-deployment-environment: ${{ env.GH_DEPLOY_ENV }}
          enable-pull-request-comment: true
          enable-commit-comment: false
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_API_ID }}
