on:
  push:
    branches:
      - jbook
  pull_request:
    branches:
      - jbook
jobs:
  run:
    name: Build Jupyter Book
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Execute notebooks and build book
        run: |
          echo ${{ secrets.EOX_REGISTRY_PASSWORD }} | docker login -u ${{ secrets.EOX_REGISTRY_USER }} --password-stdin registry.gitlab.eox.at
          docker run -v $GITHUB_WORKSPACE:/home/jovyan -u root \
            -e VIRES_TOKEN=${{ secrets.VIRES_TOKEN }} \
            registry.gitlab.eox.at/esa/vires_vre_ops/vre-swarm-notebook:0.7.5 \
            bash -c \
              '
              export CDF_LIB=/opt/conda/lib && \
              pip install --upgrade viresclient && \
              viresclient set_token https://vires.services/ows $VIRES_TOKEN && \
              viresclient set_default_server https://vires.services/ows && \
              pip install jupyter-book --ignore-installed && \
              pip install --upgrade nbconvert && \
              jupyter nbconvert --to notebook --inplace --execute --ExecutePreprocessor.timeout=1200 notebooks/* && \
              jupyter-book build .
              '
      - name: Deploy preview with netlify        
        run: netlify deploy --dir=_build/html --auth=${{ secrets.NETLIFY_AUTH_TOKEN }} --site=${{ secrets.NETLIFY_SITE_API_ID }}
